### ISSUE TITLE
AttributeError: EDGE_FUSION_RELU

### ISSUE THREAD

**Issue by 953038395** [zhangyp15/MonoFlex#14]
when use

CUDA_VISIBLE_DEVICES=0 python tools/plain_train_net.py --config runs/monoflex.yaml --ckpt model_moderate_best_soft.pth  --eval

Traceback (most recent call last):
  File "tools/plain_train_net.py", line 160, in <module>
    args=(args,),
  File "/MonoFlex/engine/launch.py", line 57, in launch
    main_func(*args)
  File "tools/plain_train_net.py", line 116, in main
    model = KeypointDetector(cfg)
  File "/MonoFlex/model/detector.py", line 23, in __init__
    self.heads = bulid_head(cfg, self.backbone.out_channels)
  File "/MonoFlex/model/head/detector_head.py", line 29, in bulid_head
    return Detect_Head(cfg, in_channels)
  File "/MonoFlex/model/head/detector_head.py", line 13, in __init__
    self.predictor = make_predictor(cfg, in_channels)
  File /MonoFlex/model/head/detector_predictor.py", line 169, in make_predictor
    return func(cfg, in_channels)
  File "/MonoFlex/model/head/detector_predictor.py", line 105, in __init__
    self.edge_fusion_relu = cfg.MODEL.HEAD.EDGE_FUSION_RELU
  File "/.conda/envs/monoflex/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: EDGE_FUSION_RELU

how to solve this problem?

**Comment by zhangyp15** [comment]
Sorry, I forgot to upload the changes of the default.py. Now the problem should be fixed.
