### ISSUE TITLE
i prepared the environment according to the README, but still reports this error:

### ISSUE THREAD

**Issue by Lan2Kailee** [zhangyp15/MonoFlex#34]
Traceback (most recent call last):
File "plain_ train_ net.py", line 25, in <module>
from model. detector import KeypointDetector
Fіlе " /hоmе/dуj /МоnоFlех/mоdеl/dеtесtоr .ру", lіnе б, іn <mоdulе>
from backbone import build_ backbone
File " /home /dyj/MonoFlex/model/backbone/_ init__ .py" , line 1, in <module>from .dla_ dcn import build_ backbone
File " /home /dyj/MonoF lex/model/backbone/dla_ dcn.py", line 16, in <module>from model. backbone . DCNv2.dcn_ v2 import DCN
File "/home/dyj/MonoFlex/nodel/backbone/DCNv2/dcn v2.py", line 13, in <nodule>import_ ext as_ backend
ImportError: /home/dyj/MonoFlex/model/backbone/DCNv2/ ext.cpython- 37я-x86 64-linux-gnu. so: undefined symbol: cudaSe tupArgunent

**Comment by micyan01** [comment]
may be your python version is not 37
