### ISSUE TITLE
Pytorch 1.7安装教程

### ISSUE THREAD

**Issue by PanJinquan** [zhangyp15/MonoFlex#46]
```bash
git clone https://github.com/zhangyp15/MonoFlex
git clone https://github.com/lbin/DCNv2 -b pytorch_1.7 # 切换到pytorch_1.7分支
# 将DCNv2代替掉MonoFlex下model/backbone/DCNv2
export CUDA_HOME=/usr/local/cuda-11.0 # 设置cuda路径
export TORCH_CUDA_ARCH_LIST="7.5"  # 降低算力
cd model/backbone/DCNv2
. make.sh
cd ../../..
python setup.py develop
```

**Comment by jackyyang-cv** [comment]
python setup.py develop命令报错：
running develop
running egg_info
creating monoflex.egg-info
writing monoflex.egg-info/PKG-INFO
writing dependency_links to monoflex.egg-info/dependency_links.txt
writing top-level names to monoflex.egg-info/top_level.txt
writing manifest file 'monoflex.egg-info/SOURCES.txt'
reading manifest file 'monoflex.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'monoflex.egg-info/SOURCES.txt'
running build_ext
building '_ext' extension
Emitting ninja build file /home/pc-111/d2workspace/lcodes/3D/MonoFlex/build/temp.linux-x86_64-3.7/build.ninja...
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1230, in _write_ninja_file_and_compile_objects
    with_cuda=with_cuda)
  File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1697, in _write_ninja_file
    assert len(sources) > 0
AssertionError

**Comment by KDJJJ** [comment]
> 

Hi,I meet the same problem,have you solved it?

**Comment by KDJJJ** [comment]
> python setup.py develop命令报错： running develop running egg_info creating monoflex.egg-info writing monoflex.egg-info/PKG-INFO writing dependency_links to monoflex.egg-info/dependency_links.txt writing top-level names to monoflex.egg-info/top_level.txt writing manifest file 'monoflex.egg-info/SOURCES.txt' reading manifest file 'monoflex.egg-info/SOURCES.txt' adding license file 'LICENSE' writing manifest file 'monoflex.egg-info/SOURCES.txt' running build_ext building '_ext' extension Emitting ninja build file /home/pc-111/d2workspace/lcodes/3D/MonoFlex/build/temp.linux-x86_64-3.7/build.ninja... Traceback (most recent call last): File "setup.py", line 66, in cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension}, File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/**init**.py", line 153, in setup return distutils.core.setup(**attrs) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/core.py", line 148, in setup dist.run_commands() File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/dist.py", line 966, in run_commands self.run_command(cmd) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/dist.py", line 985, in run_command cmd_obj.run() File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run self.install_for_development() File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development self.run_command('build_ext') File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/cmd.py", line 313, in run_command self.distribution.run_command(command) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/dist.py", line 985, in run_command cmd_obj.run() File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run _build_ext.run(self) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/command/build_ext.py", line 340, in run self.build_extensions() File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions build_ext.build_extensions(self) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions self._build_extensions_serial() File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial self.build_extension(ext) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension _build_ext.build_extension(self, ext) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension depends=ext.depends) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile with_cuda=with_cuda) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1230, in _write_ninja_file_and_compile_objects with_cuda=with_cuda) File "/home/pc-111/d1workspace/linux/anaconda3/envs/monoflex/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1697, in _write_ninja_file assert len(sources) > 0 AssertionError

这个有解决办法了吗？

**Comment by ZCMax** [comment]
Just delete `ext_modules=get_extensions()` in `setup.py` and It solves

**Comment by Senwang98** [comment]
@ZCMax @PanJinquan 
在两台服务器上都试了（3090）似乎不行
老哥们的GPU是30系列的吗
